config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "user/registrations",
                                       omniauth_callbacks: 'user/omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stocks', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friends', to: 'users#search'

  post 'add_friend', to: 'users#add_friend'
  resources :user_stocks, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :friendships
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  def self.new_from_lookup(ticker_symbol)
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    return if looked_up_stock.nil?
    price = strip_commas(looked_up_stock.l) if looked_up_stock
    new(name: looked_up_stock.name, ticker: looked_up_stock.symbol, last_price: price)
  end

  class << self
    def Stock.strip_commas(number)
      number.delete(',')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end

  def self.search(search_param)
    search_param.strip!
    search_param.downcase!
    found_users = (first_name_matches(search_param) + last_name_matches(search_param) + email_matches(search_param)).uniq
    return nil unless found_users
    found_users
  end

  def self.first_name_matches(search_param)
    matches('first_name', search_param)
  end

  def self.last_name_matches(search_param)
    matches('last_name', search_param)
  end

  def self.email_matches(search_param)
    matches('email', search_param)
  end

  def self.matches(field_name, search_param)
    User.where("#{field_name} like ?", "%#{search_param}%")
  end

  def except_current_user(users)
   users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(friend_id)
    Friendship.where(friend_id: friend_id).count < 1
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    # unless user
    #     user = User.create(name: data['name'],
    #        email: data['email'],
    #        password: Devise.friendly_token[0,20]
    #     )
    # end
    user
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def destroy
    @friendship = current_user.friendships.where(friend_id: params[:id]).first
    @friendship.destroy
    flash[:notice] = 'Friend was successfully removed'
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].blank?
      flash.now[:danger] = 'Empty search string entered'
    else
      @stock = Stock.new_from_lookup(params[:stock])
      flash.now[:danger] = "Stock with symbol #{params[:stock]} does not exist" unless @stock
    end
    respond_to do |format|
      format.js { render partial: 'users/result' }
    end
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    @stock = Stock.find_by_ticker(params[:stock_ticker])
    if @stock.nil?
      @stock = Stock.new_from_lookup(params[:stock_ticker])
      @stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: @stock)
    flash[:success] = "Stock #{@user_stock.stock.name} was successfully added to portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    @user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    @user_stock.destroy
    flash[:success] = "Stock #{@user_stock.stock.name} was successfully removed from yours portfolio"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @user_stocks = current_user.stocks
  end

  def my_friends
    @friendships = current_user.friends
  end

  def search
    if params[:search_param].blank?
      flash.now[:danger] = "You have entered an empty string"
    else
      @users = User.search(params[:search_param])
      @users = current_user.except_current_user(@users)
      flash.now[:danger] = "No users match this search criteria" if @users.empty?
    end
    respond_to do |format|
      format.js { render partial: 'friends/my_friends_result' }
    end
  end

  def show
    @user = User.find(params[:id])
    @user_stocks = @user.stocks
  end

  def add_friend
    @friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: @friend.id)

    if current_user.save
      flash[:success] = 'Friend was successfully added'
    else
      flash[:danger] = 'Friend was not added'
    end
    redirect_to my_friends_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/friends/_lookup.html.erb
<div class="row">
  <h3>Search for friends</h3>
  <%= form_tag search_friends_path, remote: true, method: :get, id: "friend-lookup-form" do %>
      <div class="col-md-10">
        <%= text_field_tag :search_param, params[:search_param], placeholder: "Enter name or email", autofocus: true,
                           class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <i class="fa fa-search"></i> Search
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/friends/_my_friends_result.html.erb
<% if params[:action] == 'search' %>
  <div class=results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>
<% if @users && @users.size > 0 %>
  <div id="friend-lookup-results" class="well results-block col-md-10">
    <table class="search-results-table col-md-12">
      <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |friend| %>
        <tr>
          <td><strong>Name: </strong><%= friend.full_name %></td>
          <td><strong>Email: </strong><%= friend.email %></td>
          <td><strong>Profile: </strong>
            <%= link_to 'View Profile', user_path(friend), class: 'btn btn-sm btn-primary' %>
            <% if current_user.not_friends_with?(friend.id) %>
              <%= link_to 'Add as friend', add_friend_path(user: current_user, friend: friend), method: :post,
                          class: 'btn btn-sm btn-primary' %></td>
            <% end %>
            </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/friends/_my_friends_result.js.erb
$('#my_friends_result').html("<%= j (render 'friends/my_friends_result.html') %>")

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <%= link_to 'Stock tracer', root_path, class: "navbar-brand" %>
    <% if current_user %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav col-md-6">
          <li><%= link_to "My portfolio", my_portfolio_path %></li>
          <li><%= link_to "My profile", edit_registration_path(current_user) %></li>
          <li><%= link_to "My friends", my_friends_path %></li>
        </ul>
        <ul class="nav navbar-right col-md-4">
          <li class="col-md-8 user-name text-right">
            <i class="fa fa-user"></i>
            <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
          </li>
          <li class="col-md-4 logout"><%= link_to("logout", destroy_user_session_path,
                                                  class: "btn btn-xs btn-danger", method: :delete) %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "StockTracer" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->

  <%= javascript_include_tag "application" %>

  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>

</head>
<body>

<%= render partial: 'layouts/navigation' %>

<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div><!--/row-->

  <footer>
    <p>&copy; Company 2018</p>
  </footer>

</div> <!-- /container -->

  <%= render partial: 'shared/google_analytics' %>
</body>
</html>

app/views/shared/_google_analytics.html.erb
<% if Rails.env.production? %>
  <script type="text/javascript">
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-116422950-1', 'auto');
  </script>
<% end %>

app/views/stocks/_list.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Symbol</th>
    <th>Current Price</th>
    <% if @user.id == current_user.id %>
      <th>Actions</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% @user_stocks.each do |user_stock| %>
    <tr>
      <td><%= user_stock.name %></td>
      <td><%= user_stock.ticker %></td>
      <td><%= user_stock.last_price %></td>
      <% if @user.id == current_user.id %>
        <td><%= link_to "Delete this stock", user_stock_path(user_stock),
                        method: :delete,
                        data: {confirm: "Are you sure?"},
                        class: "btn btn-xs btn-danger" %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/user_stocks/_user_stocks.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Symbol</th>
    <th>Current Price</th>
    <% if @user.id == current_user.id %>
      <th>Actions</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% @user_stocks.each do |user_stock| %>
    <tr>
      <td><%= user_stock.name %></td>
      <td><%= user_stock.ticker %></td>
      <td><%= user_stock.last_price %></td>
      <% if @user.id == current_user.id %>
        <td><%= link_to "Delete this stock", user_stock_path(user_stock),
                        method: :delete,
                        data: {confirm: "Are you sure?"},
                        class: "btn btn-xs btn-danger" %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/_friends_list.erb
<% @friendships.each do |friend| %>
  <tr>
    <td><%= friend.full_name %></td>
    <td><%= friend.email %></td>
    <td><%= link_to "View Profile", user_path(friend), class: "btn btn-primary btn-xs" %></td>
      <td><%= link_to "Remove friend", friendship_path(friend),
                      method: :delete,
                      data: {confirm: "Are you sure?"},
                      class: "btn btn-xs btn-danger" %>
      </td>
  </tr>
<% end %>

app/views/users/_result.html.erb
<% if params[:action] == 'search' %>
  <div class=results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>
<% if @stock %>
  <div class="well results-block">
    <strong> Symbol: </strong> <%= @stock.ticker %>
    <strong> Name: </strong> <%= @stock.name %>
    <strong> Price: </strong> <%= @stock.last_price %>
    <%= link_to "Add to my stocks", user_stocks_path(user: current_user, stock_ticker: @stock.ticker),
                class: "btn btn-xs btn-success", method: :post %>
  </div>
<% end %>

app/views/users/_result.js.erb
$('#results').html("<%= j (render 'users/result.html') %>")

app/views/users/my_friends.html.erb
<%= render 'friends/lookup' %>
<% if @friendships.size > 0 %>
  <div class="row">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @friendships.each do |friend| %>
        <tr>
          <td><%= friend.full_name %></td>
          <td><%= friend.email %></td>
          <td><%= link_to "View Profile", user_path(friend), class: "btn btn-primary btn-xs" %>
            <%= link_to "Remove friend", friendship_path(friend),
                        method: :delete,
                        data: {confirm: "Are you sure?"},
                        class: "btn btn-xs btn-danger" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="row col-lg-12">
    <p class="lead">You don't have any friends yet, Please add some!</p>
  </div>
<div id="my_friends_result">
  <%= render 'friends/my_friends_result' %>
</div>
<% end %>

app/views/users/my_portfolio.html.erb
<h3>Search for stocks</h3>
<div id="stock-lookup">
  <%= form_tag search_stocks_path, remote: true, method: :get, id: "stock-lookup-form" do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true,
                           class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <i class="fa fa-search"></i> Look up a stock
        <% end %>
      </div>
    </div>

  <% end %>
</div>
<div id="results">
  <%= render 'users/result' %>
</div>
<%= render 'user_stocks/user_stocks' %>

app/views/users/show.html.erb
<h2>User details</h2>
<dl class='dl-horizontal'>
  <dt><strong>Full Name</strong></dt>
  <dd><%= @user.full_name %></dd>
  <dt><strong>Email</strong></dt>
  <dd><%= @user.email %></dd>
</dl>
<div id="results">
  <%= render 'users/result' %>
</div>
<%= render 'user_stocks/user_stocks' %>

<%= link_to 'Back', my_friends_path, class: 'btn btn-primary' %>

app/views/welcome/index.html.erb
<h1>Welcome to the finance tracker app</h1>